[2024-09-23T00:55:53.281+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-23T00:55:53.303+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mercadolivre_scraper_to_snowflake_dag.insert_into_snowflake manual__2024-09-23T00:50:37.967988+00:00 [queued]>
[2024-09-23T00:55:53.314+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mercadolivre_scraper_to_snowflake_dag.insert_into_snowflake manual__2024-09-23T00:50:37.967988+00:00 [queued]>
[2024-09-23T00:55:53.314+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-23T00:55:53.331+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): insert_into_snowflake> on 2024-09-23 00:50:37.967988+00:00
[2024-09-23T00:55:53.347+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=475) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-23T00:55:53.350+0000] {standard_task_runner.py:72} INFO - Started process 481 to run task
[2024-09-23T00:55:53.352+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mercadolivre_scraper_to_snowflake_dag', 'insert_into_snowflake', 'manual__2024-09-23T00:50:37.967988+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/mercado_livre.py', '--cfg-path', '/tmp/tmpczf_cu2i']
[2024-09-23T00:55:53.354+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask insert_into_snowflake
[2024-09-23T00:55:53.425+0000] {task_command.py:467} INFO - Running <TaskInstance: mercadolivre_scraper_to_snowflake_dag.insert_into_snowflake manual__2024-09-23T00:50:37.967988+00:00 [running]> on host 6a22fc4abd55
[2024-09-23T00:55:53.549+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mercadolivre_scraper_to_snowflake_dag' AIRFLOW_CTX_TASK_ID='insert_into_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2024-09-23T00:50:37.967988+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-23T00:50:37.967988+00:00'
[2024-09-23T00:55:53.552+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-23T00:55:53.552+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-23T00:55:53.553+0000] {logging_mixin.py:190} INFO - Current task name:insert_into_snowflake state:running start_date:2024-09-23 00:55:53.304297+00:00
[2024-09-23T00:55:53.553+0000] {logging_mixin.py:190} INFO - Dag name:mercadolivre_scraper_to_snowflake_dag and current dag run status:running
[2024-09-23T00:55:53.553+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-23T00:55:53.567+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mercado_livre.py", line 40, in insert_into_snowflake
    products = [ProductData.from_dict(json.loads(p)) for p in json.loads(serialized_products)]
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2024-09-23T00:55:53.583+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-23T00:55:53.583+0000] {logging_mixin.py:190} INFO - Task start:2024-09-23 00:55:53.304297+00:00 end:2024-09-23 00:55:53.582369+00:00 duration:0.278072
[2024-09-23T00:55:53.584+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): insert_into_snowflake> dag:<DAG: mercadolivre_scraper_to_snowflake_dag> dagrun:<DagRun mercadolivre_scraper_to_snowflake_dag @ 2024-09-23 00:50:37.967988+00:00: manual__2024-09-23T00:50:37.967988+00:00, state:running, queued_at: 2024-09-23 00:50:37.995327+00:00. externally triggered: True>
[2024-09-23T00:55:53.584+0000] {logging_mixin.py:190} INFO - Failure caused by the JSON object must be str, bytes or bytearray, not NoneType
[2024-09-23T00:55:53.585+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=mercadolivre_scraper_to_snowflake_dag, task_id=insert_into_snowflake, run_id=manual__2024-09-23T00:50:37.967988+00:00, execution_date=20240923T005037, start_date=20240923T005553, end_date=20240923T005553
[2024-09-23T00:55:53.601+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-23T00:55:53.601+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 42 for task insert_into_snowflake (the JSON object must be str, bytes or bytearray, not NoneType; 481)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mercado_livre.py", line 40, in insert_into_snowflake
    products = [ProductData.from_dict(json.loads(p)) for p in json.loads(serialized_products)]
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2024-09-23T00:55:53.649+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-23T00:55:53.677+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-23T00:55:53.679+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
